# Generated by Django 3.2.6 on 2022-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailerApp', '0002_renderpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderpermission',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
